
#http://wiki.ros.org/move_base
#https://husarion.com/tutorials/ros-tutorials/7-path-planning/

obstacle_range: 3.0       #In this range obstacles will be considered during path planning.
raytrace_range: 3.5       #This parameter defines range in which area could be considered as free.

footprint: [[-0.40, -0.20], [-0.40, 0.20], [0.077, 0.20], [0.077, -0.20]]       #This parameter defines coordinates of Ohmni robots outline, 
                                                                                #this will considered during collision detecting. if the robot is not circular
#robot_radius: 0.17  # distance a circular robot should be clear of the obstacle
#center point considered for footprint is -> robot_base_frame: footprint 

inflation_radius: 0.5    #This parameter defines distance to obstacle where cost should be considered, 
                          #any further from obstacle than this value will be treated as no cost.
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}